### ISSUE TITLE
linsolve errors when Ntimes = Nfreqs = 1

### ISSUE THREAD

**Issue by nkern** [HERA-Team/linsolve#26]
https://github.com/HERA-Team/linsolve/blob/fe2ceb2f1b041d1a3034ec0062c8b9d73d4aa8a0/linsolve/linsolve.py#L177

This line is causing `LinearSolver` to error when `Ntimes == 1`, which seems like a basic unit test that was missed.  @jsdillon what is the reason for this `if` clause? 

[7/29 Update]: yes it is indeed only when Nfreqs = Ntimes = 1

**Comment by jsdillon** [comment]
It was meant to deal with constants with float values, rather than array values. See https://github.com/HERA-Team/linsolve/commit/e5a3dd0deaca729d12f2c523b7ea48a2b74a9cab

Do you have a minimum example of the bug you're talking about?

**Comment by nkern** [comment]
Here is an example from the test suite (that I've slightly adapted) that works
```
        x = np.arange(2, dtype=np.complex); x.shape = (2,1)
        y = np.arange(2, dtype=np.complex); y.shape = (2,1)
        z = np.arange(2, dtype=np.complex); z.shape = (2,1)
        d,w = {'x*y':x*y, 'x*z':x*z, 'y*z':y*z}, {}
        for k in list(d.keys()): w[k] = np.ones(d[k].shape)
        sol0 = {}
        for k in 'xyz': sol0[k] = eval(k) + .01
        ls = linsolve.LinProductSolver(d,sol0,w,sparse=self.sparse)
        ls.prm_order = {'x':0,'y':1,'z':2}
        sol = ls.solve()
```
In this case `Ntimes=2`. If we now change `Ntimes=1` then we get
```
        x = np.arange(1, dtype=np.complex); x.shape = (1,1)
        y = np.arange(1, dtype=np.complex); y.shape = (1,1)
        z = np.arange(1, dtype=np.complex); z.shape = (1,1)
        d,w = {'x*y':x*y, 'x*z':x*z, 'y*z':y*z}, {}
        for k in list(d.keys()): w[k] = np.ones(d[k].shape)
        sol0 = {}
        for k in 'xyz': sol0[k] = eval(k) + .01
        ls = linsolve.LinProductSolver(d,sol0,w,sparse=self.sparse)
        ls.prm_order = {'x':0,'y':1,'z':2}
        sol = ls.solve()
```
which fails with the broadcasting `ValueError` I'm seeing

**Comment by jsdillon** [comment]
Ok, so I just tested and it works fine if Ntimes == 1 but Nfreqs > 1. It also works fine if x, y, and z are all just floats.

So it's only in the case where it's 1x1 that it fails. I agree that this case should be handled more gracefully, but perhaps it's this will let you work around it for now?
