### ISSUE TITLE
linsolve needs better documentation

### ISSUE THREAD

**Issue by nkern** [HERA-Team/linsolve#6]
in order to understand how to use it...

**Comment by jsdillon** [comment]
Add more internal comments to the code.

**Comment by jsdillon** [comment]
Make some of the XXXs are turned into issues.

**Comment by jsdillon** [comment]
Break off code from __init__

**Comment by jsdillon** [comment]
Ping #hera_software channel when we're ready.

**Comment by jsdillon** [comment]
Everything here has been broken off into other issues or addressed in #10.
